version: "3.9"

services:
  backend:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes: []
    # Le variabili d'ambiente in prod verranno iniettate dal sistema di deploy

  frontend:
    build:
      context: ./frontend
      target: production
    volumes: []
    environment:
      - VITE_API_URL=${PROD_API_URL}