"""Sostituito external_id con id provider multipli e aggiunto birth_date

Revision ID: 92c73550da74
Revises: 0001
Create Date: 2026-03-26 19:55:59.428863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c73550da74'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_my_players_id'), 'my_players', ['id'], unique=False)
    op.create_index(op.f('ix_my_team_id'), 'my_team', ['id'], unique=False)
    op.add_column('scouting_players', sa.Column('api_football_id', sa.Integer(), nullable=True))
    op.add_column('scouting_players', sa.Column('transfermarkt_id', sa.String(length=50), nullable=True))
    op.add_column('scouting_players', sa.Column('fbref_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_scouting_players_api_football_id'), 'scouting_players', ['api_football_id'], unique=True)
    op.create_index(op.f('ix_scouting_players_fbref_id'), 'scouting_players', ['fbref_id'], unique=True)
    op.create_index(op.f('ix_scouting_players_id'), 'scouting_players', ['id'], unique=False)
    op.create_index(op.f('ix_scouting_players_transfermarkt_id'), 'scouting_players', ['transfermarkt_id'], unique=True)
    op.create_index(op.f('ix_team_traits_id'), 'team_traits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_traits_id'), table_name='team_traits')
    op.drop_index(op.f('ix_scouting_players_transfermarkt_id'), table_name='scouting_players')
    op.drop_index(op.f('ix_scouting_players_id'), table_name='scouting_players')
    op.drop_index(op.f('ix_scouting_players_fbref_id'), table_name='scouting_players')
    op.drop_index(op.f('ix_scouting_players_api_football_id'), table_name='scouting_players')
    op.drop_column('scouting_players', 'fbref_id')
    op.drop_column('scouting_players', 'transfermarkt_id')
    op.drop_column('scouting_players', 'api_football_id')
    op.drop_index(op.f('ix_my_team_id'), table_name='my_team')
    op.drop_index(op.f('ix_my_players_id'), table_name='my_players')
    # ### end Alembic commands ###