-- Script eseguito automaticamente al primo avvio del container PostgreSQL
-- Inserisce dati di esempio per poter testare subito l'applicazione
-- Prima creiamo la tabella
-- 1. Creazione tipi personalizzati
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'traittype') THEN
        CREATE TYPE traittype AS ENUM ('positive', 'negative', 'strength', 'weakness', 'style', 'other');
    END IF;
END $$;

-- 2. Tabella MY_TEAM (Deve essere la prima per le chiavi esterne)
CREATE TABLE IF NOT EXISTS public.my_team
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    formation VARCHAR(20),
    league VARCHAR(100),
    season VARCHAR(20),
    coach VARCHAR(100),
    budget DOUBLE PRECISION,
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

-- 3. Tabella MY_PLAYERS
CREATE TABLE IF NOT EXISTS public.my_players
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INTEGER REFERENCES public.my_team (id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    "position" VARCHAR(20),
    age INTEGER,
    preferred_foot VARCHAR(10),
    rating DOUBLE PRECISION
);

-- 4. Tabella SCOUTING_PLAYERS
CREATE TABLE IF NOT EXISTS public.scouting_players
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(50),
    name VARCHAR(100) NOT NULL,
    "position" VARCHAR(20),
    club VARCHAR(100),
    nationality VARCHAR(50),
    age INTEGER,
    preferred_foot VARCHAR(10),
    pace INTEGER,
    shooting INTEGER,
    passing INTEGER,
    dribbling INTEGER,
    defending INTEGER,
    physical INTEGER,
    xg_per90 DOUBLE PRECISION,
    xa_per90 DOUBLE PRECISION,
    progressive_passes INTEGER,
    aerial_duels_won_pct DOUBLE PRECISION,
    heading_score DOUBLE PRECISION,
    build_up_score DOUBLE PRECISION,
    defensive_score DOUBLE PRECISION,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_scouting_players_external_id
    ON public.scouting_players (external_id);

-- 5. Tabella TEAM_TRAITS
CREATE TABLE IF NOT EXISTS public.team_traits
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INTEGER NOT NULL REFERENCES public.my_team (id) ON DELETE CASCADE,
    trait_type traittype NOT NULL,
    description TEXT NOT NULL,
    priority INTEGER DEFAULT 1
);

-- 6. Tabella ALEMBIC
CREATE TABLE IF NOT EXISTS public.alembic_version
(
    version_num VARCHAR(32) PRIMARY KEY
);

-- 7. Permessi (Opzionale nel container ma utile)
ALTER TABLE IF EXISTS public.my_team OWNER TO football;
ALTER TABLE IF EXISTS public.my_players OWNER TO football;
ALTER TABLE IF EXISTS public.scouting_players OWNER TO football;
ALTER TABLE IF EXISTS public.team_traits OWNER TO football;


-- Inserisce una squadra di esempio
INSERT INTO my_team (name, formation, league, season, coach, notes)
VALUES ('FC Demo', '4-3-3', 'Serie A', '2024/2025', 'Mario Rossi',
        'Squadra di test per sviluppo')
ON CONFLICT DO NOTHING;

-- Inserisce caratteristiche di esempio
INSERT INTO team_traits (team_id, trait_type, description, priority)
VALUES
  (1, 'positive', 'Ottima organizzazione difensiva', 1),
  (1, 'positive', 'Buona velocità sulle fasce', 2),
  (1, 'negative', 'Scarsa efficacia di testa su calcio da fermo', 1),
  (1, 'negative', 'Mancanza di un centravanti fisico', 2)
ON CONFLICT DO NOTHING;

-- Inserisce giocatori di scouting di esempio
INSERT INTO scouting_players (
    external_id, name, position, club, nationality, age, preferred_foot,
    pace, shooting, passing, dribbling, defending, physical,
    xg_per90, xa_per90, aerial_duels_won_pct,
    heading_score, build_up_score, defensive_score
) VALUES
  ('EX001', 'Marco Testa', 'ST', 'AC Esempio', 'Italiana', 27, 'Right',
   72, 80, 65, 70, 40, 85, 0.55, 0.12, 68.0, 82.0, 65.0, 38.0),
  ('EX002', 'Luca Passatore', 'CM', 'FC Test', 'Italiana', 24, 'Left',
   68, 60, 88, 82, 65, 72, 0.15, 0.45, 30.0, 45.0, 80.0, 62.0),
  ('EX003', 'Marco Volante', 'LW', 'SC Veloce', 'Italiana', 22, 'Left',
   92, 75, 78, 88, 42, 70, 0.35, 0.40, 25.0, 38.0, 76.0, 40.0),
  ('EX004', 'Andrea Muro', 'CB', 'US Difesa', 'Italiana', 30, 'Right',
   55, 40, 68, 50, 88, 84, 0.05, 0.05, 75.0, 78.0, 55.0, 88.0)
ON CONFLICT (external_id) DO NOTHING;
